name: GitHub Actions Demo Pipeline

on:
    pull_request:
        branches: [ main ]
    workflow_dispatch: 

jobs:
    unit-test:
        runs-on: ubuntu-latest

        steps:
        - name: Repo Checkout
          uses: actions/checkout@v4
          with:
            ref: 'main'
        - name: Python Setup
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r src/requirements.txt
        - name: Run Tests
          run: |
            python -m unittest discover -s unit-tests -p "tests.py"